package locale

func init() {
	Register("[Member nodes to compact]:\n", "[Member nodes to compact]:\n")
	Register("- #%d produces/derives -> #%d", "- #%d produces/derives -> #%d")
	Register("\n[Lineage edges between members (parent -> child)]:\n", "\n[Lineage edges between members (parent -> child)]:\n")
	Register("\n[Common parent/context anchor: not a member; identifies the intent that produced these results]:\n", "\n[Common parent/context anchor: not a member; identifies the intent that produced these results]:\n")
	Register("Compact a group of RELATED exploration nodes into an integrated conclusion (body) so the planner can quickly understand what this area has established.\nInput is a connected subgraph:\n- Nodes: one-sentence intent/fact summaries with id, type, state, and confidence when present.\n- Relationships: lineage edges showing how one node derives from or produces another.\n- If nodes lack direct edges but share an upstream intent supplied as common parent #p, synthesize what that intent discovered. The common parent is context, not a member to compact.\nWrite the body as follows:\n1. Synthesize rather than enumerate. Follow causal relationships: which fact motivated an intent and which intent produced a conclusion. Do not copy every summary.\n2. Preserve distinctions between different conclusions instead of merging them into a vague sentence.\n3. Preserve evidence strength with observed/inferred labels. Inferred negative/uncertain conclusions remain tentative and open to verification, never definitive.\n4. Cite source node IDs after each conclusion, such as (#12,#28), so the planner can retrieve originals.\n5. State only what the input supports; introduce no invented information or judgments.\n6. Adapt length to the number of distinct conclusions, while remaining substantially shorter than all input summaries combined.\nOutput only the body.", "Compact a group of RELATED exploration nodes into an integrated conclusion (body) so the planner can quickly understand what this area has established.\nInput is a connected subgraph:\n- Nodes: one-sentence intent/fact summaries with id, type, state, and confidence when present.\n- Relationships: lineage edges showing how one node derives from or produces another.\n- If nodes lack direct edges but share an upstream intent supplied as common parent #p, synthesize what that intent discovered. The common parent is context, not a member to compact.\nWrite the body as follows:\n1. Synthesize rather than enumerate. Follow causal relationships: which fact motivated an intent and which intent produced a conclusion. Do not copy every summary.\n2. Preserve distinctions between different conclusions instead of merging them into a vague sentence.\n3. Preserve evidence strength with observed/inferred labels. Inferred negative/uncertain conclusions remain tentative and open to verification, never definitive.\n4. Cite source node IDs after each conclusion, such as (#12,#28), so the planner can retrieve originals.\n5. State only what the input supports; introduce no invented information or judgments.\n6. Adapt length to the number of distinct conclusions, while remaining substantially shorter than all input summaries combined.\nOutput only the body.")
	Register("[llm-test] %s / %s @ %s — no HTTP request sent (configuration or connection failed)", "[llm-test] %s / %s @ %s — no HTTP request sent (configuration or connection failed)")
	Register("[llm-test] %s / %s @ %s — attempt %d/%d HTTP %d\nResponse body: %s", "[llm-test] %s / %s @ %s — attempt %d/%d HTTP %d\nResponse body: %s")
	Register("(empty)", "(empty)")
	Register("…(truncated, %d bytes total)", "…(truncated, %d bytes total)")
	Register("This is a connection test. Output exactly the two characters OK, with no reasoning, explanation, or other content.", "This is a connection test. Output exactly the two characters OK, with no reasoning, explanation, or other content.")
	Register("Model returned no content (request succeeded, but no text was returned)", "Model returned no content (request succeeded, but no text was returned)")
}
