package locale

func init() {
	Register("\n\n[Operating constraints: highest priority, above ALL exploration/expansion heuristics below. Before generating any intent or taking any action, check these constraints and do not proceed if it would violate them]:", "\n\n[Operating constraints: highest priority, above ALL exploration/expansion heuristics below. Before generating any intent or taking any action, check these constraints and do not proceed if it would violate them]:")
	Register("\nAllowed operations:\n", "\nAllowed operations:\n")
	Register("\nProhibited operations:\n", "\nProhibited operations:\n")
	Register("\n(Discovering a new target/port/host outside these constraints does NOT grant authorization. Unless within the allowed scope above, record an out-of-scope fact and skip it; do not derive intents or perform actions for it.)", "\n(Discovering a new target/port/host outside these constraints does NOT grant authorization. Unless within the allowed scope above, record an out-of-scope fact and skip it; do not derive intents or perform actions for it.)")
	Register("\n\n**Finding ID contract**: finding_id identifies the independent finding record; finding_node_id identifies the exploration node. The id in list_findings/list_task_findings/node_detail/get_task_node_detail remains the exploration node ID; read the independent ID from finding_id in that same result. get_finding_traffic/bind_finding_traffic use the independent finding_id. The legacy update_finding_report finding_id argument still takes finding_node_id. Do not use the number on report_finding's first line for evidence tools, or guess another number after an ID error.", "\n\n**Finding ID contract**: finding_id identifies the independent finding record; finding_node_id identifies the exploration node. The id in list_findings/list_task_findings/node_detail/get_task_node_detail remains the exploration node ID; read the independent ID from finding_id in that same result. get_finding_traffic/bind_finding_traffic use the independent finding_id. The legacy update_finding_report finding_id argument still takes finding_node_id. Do not use the number on report_finding's first line for evidence tools, or guess another number after an ID error.")
	Register("\nBy default the reporter verifies and binds traffic before writing the report. Preserve validation commands, key output, existing real traffic IDs, and their roles in evidence so the reporter can check execution records; no extra packet lookup is required just for binding. Explicit immediate binding remains supported: traffic_refs or evidence_hint_id may supply verified references; the latter reads structured references from this task's specified hint. Any invalid reference fails the entire submission. TCP/no-packet findings do not need these optional parameters. Returned finding_id and finding_node_id identify the independent record and exploration node respectively.", "\nBy default the reporter verifies and binds traffic before writing the report. Preserve validation commands, key output, existing real traffic IDs, and their roles in evidence so the reporter can check execution records; no extra packet lookup is required just for binding. Explicit immediate binding remains supported: traffic_refs or evidence_hint_id may supply verified references; the latter reads structured references from this task's specified hint. Any invalid reference fails the entire submission. TCP/no-packet findings do not need these optional parameters. Returned finding_id and finding_node_id identify the independent record and exploration node respectively.")
	Register("\nWhen handing off a confirmed finding, retain verified traffic IDs, roles, notes, and order in the hint's traffic_refs (top-level for one hint, in each hints element for batches), and explain the specific vulnerability it proves in text. Do not discard existing traffic references and hand off text alone. Unverified candidates cannot be passed as evidence.", "\nWhen handing off a confirmed finding, retain verified traffic IDs, roles, notes, and order in the hint's traffic_refs (top-level for one hint, in each hints element for batches), and explain the specific vulnerability it proves in text. Do not discard existing traffic references and hand off text alone. Unverified candidates cannot be passed as evidence.")
	Register("\n\n**Traffic evidence handoff (optional)**: By default, the reporter binds evidence after finding registration and before report writing. Preserve validation commands, key output, existing real traffic IDs and roles in evidence, including intent_id in tasks for traceability. Do not look up extra packets just for binding. Auto/Planner must preserve references already held by the executor. add_hint/add_task_hint support traffic_refs handoff; report_finding still supports explicit immediate binding through traffic_refs/evidence_hint_id. Register TCP or no-packet findings normally. Never guess IDs or repeat probes only to capture packets.", "\n\n**Traffic evidence handoff (optional)**: By default, the reporter binds evidence after finding registration and before report writing. Preserve validation commands, key output, existing real traffic IDs and roles in evidence, including intent_id in tasks for traceability. Do not look up extra packets just for binding. Auto/Planner must preserve references already held by the executor. add_hint/add_task_hint support traffic_refs handoff; report_finding still supports explicit immediate binding through traffic_refs/evidence_hint_id. Register TCP or no-packet findings normally. Never guess IDs or repeat probes only to capture packets.")
	Register("\nWithout task context in a platform conversation, do not call report_finding directly. Hand off to the existing relevant task with add_task_hint, let its agent register the finding, and verify through list_task_findings.", "\nWithout task context in a platform conversation, do not call report_finding directly. Hand off to the existing relevant task with add_task_hint, let its agent register the finding, and verify through list_task_findings.")
	Register("\nFinish reporting/handing off existing evidence before declaring the objective complete. Do not end the task or cancel workers merely because a textual finding was registered while evidence handoff remains incomplete. Missing packets do not require waiting or forced capture.", "\nFinish reporting/handing off existing evidence before declaring the objective complete. Do not end the task or cancel workers merely because a textual finding was registered while evidence handoff remains incomplete. Missing packets do not require waiting or forced capture.")
	Register("\n\n**Automatic traffic association before reporting (enabled)**: Verify and bind traffic for this triggered finding, then write its report. Obtain explicit finding_id and finding_node_id from report_finding JSON or get_task_node_detail/list_task_findings. Read finding details, the intent's execution trace, and existing evidence; prefer real IDs handed off by the reporter. For HTTP validation with traffic tools available, filter candidates with traffic_search and verify each request/response with traffic_get. Domain/time filters do not establish ownership. Bind verified evidence in reproduction order using bind_finding_traffic(finding_id, traffic_refs), selecting baseline/proof/verification/supporting and explaining each role. Operate only on this finding; do not create duplicates or probe the target again. After binding, call get_finding_traffic again for the latest version, read the needed bodies, and pass that actually read version as evidence_version to update_finding_report (whose finding_id argument still takes finding_node_id). Do not duplicate existing bindings. For TCP, uncaptured traffic, unavailable tools, or no exact match, skip binding and write the report from textual/command evidence with an explanation. Never guess to fill gaps. If binding fails, do not claim success; retain existing evidence and explain why it was not bound.", "\n\n**Automatic traffic association before reporting (enabled)**: Verify and bind traffic for this triggered finding, then write its report. Obtain explicit finding_id and finding_node_id from report_finding JSON or get_task_node_detail/list_task_findings. Read finding details, the intent's execution trace, and existing evidence; prefer real IDs handed off by the reporter. For HTTP validation with traffic tools available, filter candidates with traffic_search and verify each request/response with traffic_get. Domain/time filters do not establish ownership. Bind verified evidence in reproduction order using bind_finding_traffic(finding_id, traffic_refs), selecting baseline/proof/verification/supporting and explaining each role. Operate only on this finding; do not create duplicates or probe the target again. After binding, call get_finding_traffic again for the latest version, read the needed bodies, and pass that actually read version as evidence_version to update_finding_report (whose finding_id argument still takes finding_node_id). Do not duplicate existing bindings. For TCP, uncaptured traffic, unavailable tools, or no exact match, skip binding and write the report from textual/command evidence with an explanation. Never guess to fill gaps. If binding fails, do not claim success; retain existing evidence and explain why it was not bound.")
	Register("Optional: verified traffic references supporting this hint's specific vulnerability, in order. After handoff, report_finding can use evidence_hint_id to include these references.", "Optional: verified traffic references supporting this hint's specific vulnerability, in order. After handoff, report_finding can use evidence_hint_id to include these references.")
	Register("Actual traffic ID", "Actual traffic ID")
	Register("The conclusion this traffic supports", "The conclusion this traffic supports")
	Register("evidence_hint_id=%d must be a hint node from this task (inherited hints cannot be bound directly)", "evidence_hint_id=%d must be a hint node from this task (inherited hints cannot be bound directly)")
	Register("\n\n**Finding traffic evidence (optional)**: When reporting with report_finding, use traffic_refs to bind actual HTTP request/response IDs in reproduction order only after inspecting and confirming they support the finding. Domain/time filters select candidates, not presumed associations. For TCP/non-HTTP findings, absent capture, or no exact match, omit traffic_refs or pass []; retain command output, logs, or other verifiable evidence and explain missing bindings where appropriate. Do not guess IDs or repeat probes merely to capture packets.", "\n\n**Finding traffic evidence (optional)**: When reporting with report_finding, use traffic_refs to bind actual HTTP request/response IDs in reproduction order only after inspecting and confirming they support the finding. Domain/time filters select candidates, not presumed associations. For TCP/non-HTTP findings, absent capture, or no exact match, omit traffic_refs or pass []; retain command output, logs, or other verifiable evidence and explain missing bindings where appropriate. Do not guess IDs or repeat probes merely to capture packets.")
	Register("Tool %s internal error: %v (this call failed; try different arguments or another tool)", "Tool %s internal error: %v (this call failed; try different arguments or another tool)")
	Register("Execution failed: ", "Execution failed: ")
	Register("Could not enable noa compaction; falling back to built-in compaction: ", "Could not enable noa compaction; falling back to built-in compaction: ")
}
